import { Inter } from "next/font/google";
import Link from "next/link";
import Navbar from "./companent/Navbar";
import "./globals.css";
import Footer from "./companent/Footer";
import Sidebar from "./companent/SideBar";
import { Button } from "antd";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "./queryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project Management Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <div className="flex flex-col min-h-screen">
            <Navbar></Navbar>
            <div className="flex flex-col md:flex-row flex-1">
              <div className="md:w-1/6 shadow h-svh">
                <Sidebar></Sidebar>
              </div>
              <div className="md:w-5/6">{children}</div>
            </div>
            <Footer></Footer>
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
